{{- define "zwavejs2mqtt.ingress" -}}
{{- $addon := .Data -}}
{{- $values := .Values -}}
{{- $addonName := .AddonName -}}
{{- if and $addon.enabled $addon.ingress.main.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-ingress
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ $addon.ingress.main.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
                port:
                  number: {{ $addon.service.main.ports.http.port }}
{{- end }}
{{- end }}
