{{- define "zwavejs2mqtt.volumes" -}}
{{- $addon := .Data -}}
{{- $values := .Values -}}
{{- $addonName := .AddonName -}}
{{- if $addon.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config-pv
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ $addon.persistence.config.capacity.storage }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ $addon.persistence.config.mountPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config-pvc
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $addon.persistence.config.capacity.storage }}
  storageClassName: manual
{{- end }}
{{- end }}