apiVersion: v2
name: homeassistant
description: A Helm chart for Kubernetes
type: application 
version: 0.1.0
appVersion: 2023.6.3
kubeVersion: ">=1.22.0-0"
keywords:
  - home-automation
  - mqtt
  - iot
  - internet-of-things
sources:
  - https://github.com/home-assistant/core
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: Fixed icon URL
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/home-assistant/core
