# Default values for homeassistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# namePrefix will add extra name for you pods.
# if not used pods will get release name + pod name. otherwise it will be release name + name prefix + pod name
# for example myHomeassistant-service and if using namePrefix: skeletor it will be myHomeassistant-skeletor-service
namePrefix: ""
namespace: homeassistant

env:
  TZ: UTC
  #ENV_VAR_NAME_1: ENV_VAR_VALUE_1
  #ENV_VAR_NAME_2: ENV_VAR_VALUE_2

image:
  # -- image repository
  repository: ghcr.io/home-assistant/home-assistant
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag Overrides the image tag whose default is the chart appVersion.
  tag: 2023.8


service:
  main:
    ports:
      http:
        port: 8123
  type: ClusterIP

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    hosts:
      - host: homeassistant.local
        paths:
          - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local
serviceAccount:
  name: ""
  create: true

# -- Enable devices to be discoverable
hostNetwork: true

# -- When hostNetwork is true set dnsPolicy to `ClusterFirstWithHostNet`
dnsPolicy: ClusterFirstWithHostNet

podSecurityContext: {}
  # fsGroup: 1000
nodeSelector: {}
tolerations: []


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

volumeMounts: []
# - name: config
#   mountPath: /config

volumes: []
# - name: config
#   hostPath:
#     path: /etc/homeassistant
#     type: DirectoryOrCreate

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  config:
    enabled: true
    retain: true
    storageClassName: "standard"
    size: 2Gi
      
addons:
  smarterdevicemanager:
    enabled: true
    image:
      repository: registry.gitlab.com/arm-research/smarter/smarter-device-manager
      tag: v1.20.11
      pullPolicy: IfNotPresent
    config: |
      - devicematch: ^ttyUSB[0-9]*$
        nummaxdevices: 6
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    termination:
      messagePath: /var/log/termination-log
    persistence:
      devfs:
        enabled: true
        hostPath: /dev
      sysfs:
        enabled: true
        hostPath: /sys
      kubeletsockets:
        enabled: true
        hostPath: "/var/lib/kubelet/device-plugins"

    # -- Custom priority class for different treatment by the scheduler
    # Setting this is not necessary, but it is recommended.
    # [[ref]](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/)
    priorityClassName: system-node-critical

    # -- Configure the securityContext for this pod
    # [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
    # @default -- See values.yaml
    securityContext:
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

  zwavejs2mqtt:
    enabled : true
    image:
      pullPolicy: IfNotPresent
      repository: zwavejs/zwavejs2mqtt
      tag: 8.22.0
    ingress:
      main:
        enabled: true
        host: zwave.homessistant.local
    persistence:
      config:
        enabled: true
        mountPath: /usr/src/app/store
      usb:
        enabled: true
        hostPath: /dev/ttyUSB1
        type: hostPath
    resources:
      limits:
        smarter-devices/ttyUSB1: 1
      requests:
        smarter-devices/ttyUSB1: 1
    securityContext:
      privileged: true
    service:
      main:
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000 

  zigbee2mqtt:
    enabled: true
    image:
      repository: koenkk/zigbee2mqtt
      tag: latest
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        host: zigbee.homessistant.local
    persistence:
      config:
        enabled: true
        mountPath: /app/data
    service:
      main:
        ports:
          http:
            port: 8080

    resources:
 #     limits:
 #       cpu: 500m
 #       memory: 512Mi
 #     requests:
 #       cpu: 100m
 #       memory: 256Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    env:
    # -- Set the data folder for Zigbee2MQTT.
      ZIGBEE2MQTT_DATA: /data