apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: {{ include "homeassistant.namespace" . }}
  name: {{ include "homeassistant.fullname" . }}-ingress
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  routes:
    - match: Host(`homeassistant.local`)
      kind: Rule
      services:
        - name: {{ include "homeassistant.fullname" . }}-main
          port: {{ .Values.service.main.ports.http.port }}
      middlewares:
        - name: {{ include "homeassistant.fullname" . }}-redirectscheme

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "homeassistant.fullname" . }}-redirectscheme
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: http
    port: "{{ .Values.service.main.ports.http.port | toString }}"