apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homeassistant.fullname" . }}-main
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  rules:
    - host: homeassistant.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeassistant.fullname" . }}-main
                port:
                  number: {{ .Values.service.main.ports.http.port }}
  {{- if .Values.ingress.main.tls }}
  tls:
    - hosts:
        - homeassistant.local
      secretName: chart-example.local-tls
  {{- end }}
