apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-config
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default .Values.persistence.config.size "1Gi" }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ default .Values.persistence.config.storageClassName "standard" }}
  {{- end }}
