{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
{{- end }}
