apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}-main
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.main.ports.http.port }}
      targetPort: http
  type: {{ .Values.service.type }}
