{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "homeassistant.fullname" . }}-configmap-reader
  namespace: {{ include "homeassistant.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "homeassistant.fullname" . }}-configmap-reader-binding
  namespace: {{ include "homeassistant.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ include "homeassistant.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "homeassistant.fullname" . }}-configmap-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homeassistant.fullname" . }}-pv-list-cluster-role
  namespace: {{ include "homeassistant.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["list", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homeassistant.fullname" . }}-pv-list-cluster-role-binding
  namespace: {{ include "homeassistant.namespace" . }}
subjects:
- kind: ServiceAccount
  name: homeassistant
  namespace: homeassistant
roleRef:
  kind: ClusterRole
  name: {{ include "homeassistant.fullname" . }}-pv-list-cluster-role
  apiGroup: rbac.authorization.k8s.io




{{- end }}
