{{- $addon := .Values.addons.smarterdevicemanager -}}
{{- $addonName := "smarterdevicemanager" -}}
{{- if $addon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
data:
  conf.yaml: |-
    {{ $addon.config | nindent 4 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  selector:
    matchLabels:
      app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  template:
    metadata:
      name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
      labels:
        app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
    spec:
      priorityClassName: {{ $addon.priorityClassName }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: {{ $addon.dnsPolicy }}
      hostNetwork: {{ $addon.hostNetwork }}
      serviceAccountName: {{ include "homeassistant.fullname" . }}
      automountServiceAccountToken: true
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: true
      containers:
      - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
        image: {{ $addon.image.repository }}:{{ $addon.image.tag }}
        imagePullPolicy: {{ $addon.image.pullPolicy }}
        resources:
          limits:
            cpu: 100m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 15Mi
        volumeMounts:
          - name: config
            mountPath: /root/config/conf.yaml
            subPath: conf.yaml
          - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-device-plugin
            mountPath: {{ $addon.persistence.deviceplugin.hostPath }}
          - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-devfs
            mountPath: {{ $addon.persistence.devfs.hostPath }}
          - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-sysfs
            mountPath: {{ $addon.persistence.sysfs.hostPath }}
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          # readOnlyRootFilesystem: true
          # runAsNonRoot: true
          # runAsUser: 1000
        {{- if  $addon.probes.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: {{ $addon.probes.liveness.httpGet.path }}
            port: {{ $addon.probes.liveness.port }}
            scheme: HTTP
          initialDelaySeconds: {{ $addon.probes.liveness.initialDelay }}
          timeoutSeconds: {{ $addon.probes.liveness.timeout }}
          periodSeconds: {{ $addon.probes.liveness.period }}
          successThreshold: 1
          failureThreshold: 10
        {{- end }}
        {{- if  $addon.probes.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: {{ $addon.probes.readiness.httpGet.path }}
            port: {{ $addon.probes.readiness.port }}
            scheme: HTTP
          initialDelaySeconds: {{ $addon.probes.readiness.initialDelay }}
          timeoutSeconds: {{ $addon.probes.readiness.timeout }}
          periodSeconds: {{ $addon.probes.readiness.period }}
          successThreshold: 1
          failureThreshold: 10
        {{- end }}
        {{- if  $addon.probes.startup.enabled }}
        startupProbe:
          httpGet:
            path: {{ $addon.probes.startup.httpGet.path }}
            port: {{ $addon.probes.startup.port }}
            scheme: HTTP
          initialDelaySeconds: {{ $addon.probes.startup.initialDelay }}
          timeoutSeconds: {{ $addon.probes.startup.timeout }}
          periodSeconds: {{ $addon.probes.startup.period }}
          successThreshold: 1
          failureThreshold: 10
        {{- end }}  
      volumes:
        - name: config
          configMap:
            name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config
        - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-device-plugin
          hostPath:
            path:  {{ $addon.persistence.deviceplugin.hostPath }}
        - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-devfs
          hostPath:
            path: {{ $addon.persistence.devfs.hostPath }}
        - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-sysfs
          hostPath:
            path: {{ $addon.persistence.sysfs.hostPath }}
{{- end }}