apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "homeassistant.fullname" . }}  # Specify a unique serviceName for the Headless Service
  replicas: 1  # You can set this to 1 to ensure only one Pod runs
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always  # Set the restart policy to "Always"
      serviceAccountName: {{ include "homeassistant.fullname" . }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.main.ports.http.port }}
          {{- if  .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.httpGet.path }}
              port: {{ .Values.probes.liveness.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelay }}
            timeoutSeconds: {{ .Values.probes.liveness.timeout }}
            periodSeconds: {{ .Values.probes.liveness.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          {{- if  .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.httpGet.path }}
              port: {{ .Values.probes.readiness.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelay }}
            timeoutSeconds: {{ .Values.probes.readiness.timeout }}
            periodSeconds: {{ .Values.probes.readiness.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          {{- if  .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.httpGet.path }}
              port: {{ .Values.probes.startup.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.startup.initialDelay }}
            timeoutSeconds: {{ .Values.probes.startup.timeout }}
            periodSeconds: {{ .Values.probes.startup.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          env:
          {{- range $key, $value := .Values.env }}
          {{- if ne $value "" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- else }}
            # - name: {{ $key }}
            #   value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/homeassistant
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "homeassistant.fullname" . }}-config
