apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "homeassistant.fullname" . }}  # Specify a unique serviceName for the Headless Service
  replicas: 1  # You can set this to 1 to ensure only one Pod runs
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always  # Set the restart policy to "Always"
      serviceAccountName: {{ include "homeassistant.serviceAccountName" . }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.main.ports.http.port }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          {{- range $key, $value := .Values.env }}
          {{- if ne $value "" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- else }}
            # - name: {{ $key }}
            #   value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/homeassistant
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "homeassistant.fullname" . }}-config

{{/* Include the addons.yaml template */}}
{{ include "addons.helper" .Values }}