{{- $addon := .Values.addons.vscode -}}
{{- $addonName := "vscode" -}}
{{- $namespace := .Release.Namespace -}}
{{- $fullName := include "homeassistant.fullname" . }}
{{- $addonNames := "" }}
{{- $pvcNames := "" }}
{{- $mountPath := "" }}
{{- $mainPvc := .Values.persistence.config.retain }}

{{- range $addon, $addonConfig := .Values.addons }}
  {{- if and $addonConfig.enabled $addonConfig.persistence.retain }}
    
    {{- if ne $addonNames "" }}
      {{- $addonNames = printf "%s,%s" $addonNames $addon }}
    {{- else }}
      {{- $addonNames = printf "%s" $addon }}
    {{- end }}
    
    {{- if ne (len $pvcNames) 0 }}
      {{- $pvcNames = printf "%s,%s-%s-config-pvc" $pvcNames $fullName $addon }}
    {{- else }}
      {{- $pvcNames = printf "%s-%s-config-pvc" $fullName $addon }}
    {{- end }}
    
    {{- if ne (len $mountPath) 0 }}
      {{- $mountPath = printf "%s,%s" $mountPath $addonConfig.persistence.config.mountPath }}
    {{- else }}
      {{- $mountPath = printf "%s" $addonConfig.persistence.config.mountPath }}
    {{- end }}
  
  {{- end }}
{{- end }}
{{- if $mainPvc }}
  {{- if ne $addonNames "" }}
      {{- $addonNames = printf "%s,%s" $addonNames $fullName }}
  {{- else }}
      {{- $addonNames = printf "%s" $fullName }}
  {{- end }}
  {{- if ne (len $pvcNames) 0 }}
    {{- $pvcNames = printf "%s,%s-config" $pvcNames $fullName }}
  {{- else }}
    {{- $pvcNames = printf "%s-config" $fullName }}
  {{- end }}
  
  {{- if ne (len $mountPath) 0 }}
    {{- $mountPath = printf "%s,%s" $mountPath .Values.volumeMounts.mountPath }}
  {{- else }}
    {{- $mountPath = printf "%s" .Values.volumeMounts.mountPath }}
  {{- end }}
{{- end }}
{{- if $addon.enabled }}
{{- if not $addon.persistence.retain }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config-pvc
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $addon.persistence.config.capacity.storage }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  replicas: {{ $addon.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  template:
    metadata:
      labels:
        app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
    spec:
      volumes:
        
        {{- if gt (len $addonNames) 0 }}
          {{- range $index, $name := split "," $addonNames }}
          {{- $claim := index (split "," $pvcNames) $index }}
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ $claim }}
          {{- end }}
        {{- end }}
      containers:
        - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
          image: "{{ $addon.image.repository }}:{{ $addon.image.tag }}"
          imagePullPolicy: {{ $addon.image.pullPolicy }}
          ports:
            {{- range $key, $port := $addon.service.main.ports }}
            - name: {{ $key }}
              containerPort: {{ $port.targetPort }}
            {{- end }}
          env:
            - name: TZ
              value: {{ .Values.env.TZ }}
           {{- range $addon.env }}
            {{- if hasKey . "name" }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- if $addon.resources }}
          resources:
          {{- toYaml $addon.resources | nindent 12 }} 
          {{- end }}
          volumeMounts:
 
            {{- if gt (len $addonNames) 0 }}
              {{- range $index, $name := split "," $addonNames }}
              {{- $path := index (split "," $mountPath) $index }}
            - name: {{ $name }}
              mountPath: {{ $path }}
              {{- end }}
            {{- end }}
          {{- if  $addon.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $addon.probes.liveness.httpGet.path }}
              port: {{ $addon.probes.liveness.port }}
              scheme: HTTP
            initialDelaySeconds: {{ $addon.probes.liveness.initialDelay }}
            timeoutSeconds: {{ $addon.probes.liveness.timeout }}
            periodSeconds: {{ $addon.probes.liveness.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          {{- if  $addon.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $addon.probes.readiness.httpGet.path }}
              port: {{ $addon.probes.readiness.port }}
              scheme: HTTP
            initialDelaySeconds: {{ $addon.probes.readiness.initialDelay }}
            timeoutSeconds: {{ $addon.probes.readiness.timeout }}
            periodSeconds: {{ $addon.probes.readiness.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          {{- if  $addon.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ $addon.probes.startup.httpGet.path }}
              port: {{ $addon.probes.startup.port }}
              scheme: HTTP
            initialDelaySeconds: {{ $addon.probes.startup.initialDelay }}
            timeoutSeconds: {{ $addon.probes.startup.timeout }}
            periodSeconds: {{ $addon.probes.startup.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}  
          {{- if $addon.securityContext }}
          securityContext:
            privileged: {{ $addon.securityContext.privileged }}
          {{- end }}
      restartPolicy: {{ $addon.restartPolicy }}
      dnsPolicy: {{ $addon.dnsPolicy }}
      hostNetwork: {{ $addon.hostNetwork }}
      serviceAccountName: {{ include "homeassistant.fullname" . }}
      automountServiceAccountToken: {{ $addon.automountServiceAccountToken }}
      schedulerName: {{ $addon.schedulerName }}
      enableServiceLinks: {{ $addon.enableServiceLinks }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  selector:
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
  ports:
    {{- range $key, $port := $addon.service.main.ports }}
    - name: {{ $key }}
      protocol: TCP
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
  type: {{ $addon.service.type }}
---
{{- if $addon.ingress.main.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-ingress
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  rules:
    - host: {{ $addon.ingress.main.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
                port:
                  number: {{ $addon.service.main.ports.http.port }}
{{- end }}
{{- end }}
