{{- $addon := .Values.addons.zigbee2mqtt -}}
{{- $addonName := "zigbee2mqtt" -}}
{{- if $addon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
data:
  configuration.yaml: |-
    {{ $addon.config | nindent 4 }}
---
{{- if not $addon.persistence.retain }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config-pvc
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $addon.persistence.config.capacity.storage }}
{{- end }}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  replicas: {{ $addon.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  template:
    metadata:
      labels:
        app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config-pvc
        - name: configmap-volume
          configMap:
            name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config
      initContainers:
          - name: copy-config
            image: busybox:latest
            command: ['sh', '-c', 'cp -f /configmap-data/ /app/data/']
            volumeMounts:
              - name: configmap-volume
                mountPath: /configmap-data  
              - name: config
                mountPath: /app/data 
      containers:
        - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
          image: "{{ $addon.image.repository }}:{{ $addon.image.tag }}"
          imagePullPolicy: {{ $addon.image.pullPolicy }}
          ports:
            {{- range $key, $port := $addon.service.main.ports }}
            - name: {{ $key }}
              containerPort: {{ $port.port }}
            {{- end }}
          env:
            - name: TZ
              value: {{ .Values.env.TZ }}
           {{- range $key, $val := $addon.env }}   
            - name: {{ $key }}
              value: {{ $val.value }}
          {{- end }}
          {{- if $addon.resources }}
          resources:
          {{- toYaml $addon.resources | nindent 12 }} # Update this line to remove "smarter-devices/ttyUSB1" and "smarter-devices/ttyUSB0"
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ $addon.persistence.config.mountPath }}
          {{- if  $addon.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $addon.probes.liveness.httpGet.path }}
              port: {{ $addon.probes.liveness.port }}
              scheme: HTTP
            initialDelaySeconds: {{ $addon.probes.liveness.initialDelay }}
            timeoutSeconds: {{ $addon.probes.liveness.timeout }}
            periodSeconds: {{ $addon.probes.liveness.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          {{- if  $addon.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $addon.probes.readiness.httpGet.path }}
              port: {{ $addon.probes.readiness.port }}
              scheme: HTTP
            initialDelaySeconds: {{ $addon.probes.readiness.initialDelay }}
            timeoutSeconds: {{ $addon.probes.readiness.timeout }}
            periodSeconds: {{ $addon.probes.readiness.period }}
            successThreshold: 1
            failureThreshold: 10
          {{- end }}
          {{- if  $addon.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ $addon.probes.startup.httpGet.path }}
              port: {{ $addon.probes.startup.port }}
              scheme: HTTP
            initialDelaySeconds: {{ $addon.probes.startup.initialDelay }}
            timeoutSeconds: {{ $addon.probes.startup.timeout }}
            periodSeconds: {{ $addon.probes.startup.period }}
            successThreshold: 1
            failureThreshold: 10
        {{- end }}  
          {{- if $addon.securityContext }}
          securityContext:
            privileged: true
          {{- end }}
      restartPolicy: {{ $addon.restartPolicy }}
      dnsPolicy: {{ $addon.dnsPolicy }}
      hostNetwork: {{ $addon.hostNetwork }}
      serviceAccountName: {{ include "homeassistant.fullname" . }}
      automountServiceAccountToken: {{ $addon.automountServiceAccountToken }}
      schedulerName: {{ $addon.schedulerName }}
      enableServiceLinks: {{ $addon.enableServiceLinks }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  selector:
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
  ports:
    {{- range $key, $port := $addon.service.main.ports }}
    - name: {{ $key }}
      protocol: TCP
      port: {{ $port.port }}
      targetPort: {{ $key }}
    {{- end }}
  type: {{ $addon.service.type }}
---
{{- if $addon.ingress.main.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-ingress
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  rules:
    - host: {{ $addon.ingress.main.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
                port:
                  number: {{ $addon.service.main.ports.http.port }}
{{- end }}
{{- end }}
