{{- $addon := .Values.addons.zigbee2mqtt -}}
{{- $addonName := "zigbee2mqtt" -}}
{{- if $addon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
data:
  configuration.yaml: |-
    {{ $addon.config | nindent 4 }}
---
{{- if $addon.persistence.retain }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-storage
  namespace: {{ include "homeassistant.namespace" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config-pvc
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $addon.persistence.config.capacity.storage }}
  {{- if $addon.persistence.retain }}
  selector:
    matchLabels:
      app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  storageClassName: manual-storage
  {{- end }}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  replicas: {{ $addon.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  template:
    metadata:
      labels:
        app: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-config
      containers:
        - name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
          image: "{{ $addon.image.repository }}:{{ $addon.image.tag }}"
          imagePullPolicy: {{ $addon.image.pullPolicy }}
          ports:
            {{- range $key, $port := $addon.service.main.ports }}
            - name: {{ $key }}
              containerPort: {{ $port.port }}
            {{- end }}
          env:
            - name: TZ
              value: {{ .Values.env.TZ }}
            - name: ZIGBEE2MQTT_DATA
              value: /app/data
          {{- if $addon.resources }}
          resources:
          {{- toYaml $addon.resources | nindent 12 }} # Update this line to remove "smarter-devices/ttyUSB1" and "smarter-devices/ttyUSB0"
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ $addon.persistence.config.mountPath }}
              subPath: configuration.yaml
          livenessProbe:
            tcpSocket:
              port: {{ $addon.service.main.ports.http.port }}
          readinessProbe:
            tcpSocket:
              port: {{ $addon.service.main.ports.http.port }}
          startupProbe:
            tcpSocket:
              port: {{ $addon.service.main.ports.http.port }}
          {{- if $addon.securityContext }}
          securityContext:
            privileged: true
          {{- end }}
      restartPolicy: {{ $addon.restartPolicy }}
      dnsPolicy: {{ $addon.dnsPolicy }}
      serviceAccountName: {{ include "homeassistant.serviceAccountName" . }}
      automountServiceAccountToken: {{ $addon.automountServiceAccountToken }}
      schedulerName: {{ $addon.schedulerName }}
      enableServiceLinks: {{ $addon.enableServiceLinks }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $key, $port := $addon.service.main.ports }}
    - name: {{ $key }}
      protocol: TCP
      port: {{ $port.port }}
      targetPort: {{ $key }}
    {{- end }}
  type: {{ $addon.service.type }}
---
{{- if $addon.ingress.main.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-ingress
  namespace: {{ include "homeassistant.namespace" . }}
  labels: 
    app: {{ include "homeassistant.fullname" . }}-{{ $addonName }} 
spec:
  rules:
    - host: {{ $addon.ingress.main.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}
                port:
                  number: {{ $addon.service.main.ports.http.port }}
{{- end }}
{{- end }}
