{{- define "smarterdevicemanager.persistentvolumes" -}}
{{- $addon := .Data -}}
{{- $values := .Values -}}
{{- $addonName := .AddonName -}}
{{- if $addon.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-devfs
  namespace: {{ include "homeassistant.namespace" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  capacity:
    storage:  {{ $addon.persistence.devfs.capacity.storage }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ $addon.persistence.devfs.hostPath }}
{{- end }}

{{- if $addon.persistence.sysfs.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-sysfs
spec:
  capacity:
    storage: {{ $addon.persistence.sysfs.capacity.storage }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ $addon.persistence.sysfs.hostPath }}
{{- end }}

{{- if $addon.persistence.kubeletsockets.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-{{ $addonName }}-kubeletsockets
spec:
  capacity:
    storage:  {{ $addon.persistence.kubeletsockets.capacity.storage }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "{{ $addon.persistence.kubeletsockets.hostPath }}"
{{- end }}
{{- end }}



