{{- define "addons.templates.services" -}}
{{- if not .enabled }}
# fuck me
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ulf
  name: ulf-controller
  namespace: unifi
spec:
  type: NodePort
  selector:
    app: ulf-controller
  ports:
    - name: "udp-port-3478"
      port: 3478
      protocol: UDP
      targetPort: 3478
      nodePort: 30001  # Choose an available node port that doesn't conflict
  externalIPs:
    - "192.168.3.23"
{{- end }}
{{- end }}
